#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh --forest
feh --bg-fill /usr/share/backgrounds/bspwm/wallpaper.jpg
picom &

bspc monitor -d 1 2 3 4 5 6 7 8 9
#bspc monitor -d I II III IV V


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^3'
bspc rule -a spotify desktop='^9'
bspc rule -a kitty desktop='^1'
bspc rule -a TelegramDesktop desktop='^4'
#bspc rule -a Screenkey manage=off

